import { FilterEntry, ObjectEntry, TagEntry, PlatformOSDocset } from './types';
import { UNDOCUMENTED_FILTERS } from './undocumented-filters';
import { undocumentedTagEntries } from './undocumented-tags';
import { memo } from './utils';

const toFilterEntry = (name: string): FilterEntry => ({ name });

const expandAliases = (entries: FilterEntry[]): FilterEntry[] => {
  return entries.flatMap((entry) => {
    const aliases: string[] = (entry as any).aliases ?? [];
    return aliases.map((alias) => ({ ...entry, name: alias }));
  });
};

/**
 * The platformOS API has a data inconsistency where some deprecated filters
 * have `deprecated: false` but `deprecation_reason: "true"` (the string).
 * Normalize these to have `deprecated: true` with no deprecation reason message.
 */
const normalizeDeprecation = (entry: FilterEntry): FilterEntry => {
  if (!entry.deprecated && entry.deprecation_reason === 'true') {
    return { ...entry, deprecated: true, deprecation_reason: undefined };
  }
  return entry;
};

export class AugmentedPlatformOSDocset implements PlatformOSDocset {
  constructor(private platformosDocset: PlatformOSDocset) {}
  graphQL = memo(async (): Promise<string | null> => {
    return await this.platformosDocset.graphQL();
  });

  public isAugmented = true;

  filters = memo(async (): Promise<FilterEntry[]> => {
    const officialFilters = (await this.platformosDocset.filters()).map(normalizeDeprecation);
    return [
      ...officialFilters,
      ...expandAliases(officialFilters),
      // Generated by probing a real instance — see `undocumented-filters.ts`. Never
      // hand-edit: an unverified name here silences `UnknownFilter`, so broken code
      // clears the write gate and raises at runtime.
      ...UNDOCUMENTED_FILTERS.map(toFilterEntry),
    ];
  });

  objects = memo(async (): Promise<ObjectEntry[]> => {
    return await this.platformosDocset.objects();
  });

  liquidDrops = memo(async (): Promise<ObjectEntry[]> => {
    return (await this.platformosDocset.objects()).filter((obj) => {
      if (!obj.access) {
        return true;
      }

      if (obj.deprecated) {
        return false;
      }

      // objects that are accessible outside Global context
      return !obj.access.global || (obj.access.global && obj.access.parents.length > 0);
    });
  });

  tags = memo(async (): Promise<TagEntry[]> => {
    const documented = await this.platformosDocset.tags();
    // Derived from the platform's own `register_tag` registry plus a short hand-verified
    // list of sub-tags — see `undocumented-tags.ts`. Never hand-edit either: a name that
    // is NOT a real tag silences `UnknownTag`, and a real tag missing from them is a
    // BLOCKING refusal of code the platform runs.
    return [...documented, ...undocumentedTagEntries(documented)];
  });
}
