// WARNING:
// This file was generated by "scripts/verify-registered-tags.mjs".
// Do not modify manually. Your changes will be overwritten.
//
// Transcribed from the platform's own Liquid tag registry — the only non-test file
// calling `register_tag`. Liquid's built-in tags come from the gem and are therefore
// absent here; everything below is a platformOS addition.
//
// Registry:  /home/ecgtheow/Work/desksnearme-release-candidate/config/initializers/liquid_view.rb
// Generated: 2026-08-03

/** One `register_tag` line, exactly as the platform wrote it. */
export interface RegisteredTag {
  /** The tag name authors write, e.g. `graphql` in `{% graphql %}`. */
  name: string;

  /**
   * The Ruby class handling it.
   *
   * Load-bearing, not decoration: two names sharing a handler are the SAME TAG under two
   * spellings. That is how the aliases are identified without guessing from the `_rc`
   * suffix — `context_rc` and `context` are both `Liquify::Tags::ContextTag`.
   */
  handler: string;

  /** Trailing comment on the registration line, if any — e.g. `TODO: remove`. */
  comment?: string;

  /** Comment on the line immediately above, if any. Cleared by any non-comment line. */
  precedingComment?: string;
}

/**
 * Every Liquid tag platformOS registers.
 *
 * THE VOCABULARY, not a supplement to it. Consulted by {@link AugmentedPlatformOSDocset},
 * which injects the entries the injected docset does not already carry so `UnknownTag`
 * stops refusing them. Membership matters in both directions:
 *
 *   - a name here that the platform does NOT register silences `UnknownTag` for it, so a
 *     genuinely misspelled tag clears the write gate and fails the whole deploy;
 *   - a registered name MISSING from here is reported as an unknown tag, and since
 *     `LiquidHTMLSyntaxError` blocks, the agent cannot write working code at all.
 *
 * Which of these are aliases, which are deprecated and which are merely undocumented is
 * NOT decided here — see `AugmentedPlatformOSDocset`. This file is a transcription, and
 * keeping it one is what lets it be regenerated and diffed.
 */
export const REGISTERED_TAGS: readonly RegisteredTag[] = [
  { name: 'background', handler: 'Liquify::Tags::BackgroundTag' },
  { name: 'cache', handler: 'Liquify::Tags::CacheTag' },
  { name: 'content_for', handler: 'Liquify::Tags::ContentForTag' },
  { name: 'context', handler: 'Liquify::Tags::ContextTag' },
  { name: 'context_rc', handler: 'Liquify::Tags::ContextTag' },
  { name: 'execute_query', handler: 'Liquify::Tags::ExecuteQueryTag' },
  { name: 'export', handler: 'Liquify::Tags::ExportTag' },
  { name: 'form', handler: 'Liquify::Tags::FormForTag' },
  { name: 'function', handler: 'Liquify::Tags::FunctionTag' },
  { name: 'function_rc', handler: 'Liquify::Tags::FunctionTag', comment: 'TODO: remove' },
  { name: 'graphql', handler: 'Liquify::Tags::GraphqlTag' },
  {
    name: 'hash_assign',
    handler: 'Liquify::Tags::HashAssignTag',
    comment: 'DEPRECATED: Use {% assign %} instead',
  },
  { name: 'include_form', handler: 'Liquify::Tags::IncludeFormTag' },
  { name: 'log', handler: 'Liquify::Tags::LogTag' },
  { name: 'parse_json', handler: 'Liquify::Tags::ParseJsonTag' },
  { name: 'print', handler: 'Liquify::Tags::PrintTag' },
  { name: 'query_graph', handler: 'Liquify::Tags::QueryGraphTag' },
  { name: 'redirect_to', handler: 'Liquify::Tags::RedirectToTag' },
  {
    name: 'render_form',
    handler: 'Liquify::Tags::IncludeFormTag',
    precedingComment: 'For semi-backwards compatibility, for now...',
  },
  { name: 'response_headers', handler: 'Liquify::Tags::ResponseHeadersTag' },
  { name: 'response_status', handler: 'Liquify::Tags::ResponseStatusTag' },
  { name: 'return', handler: 'Liquify::Tags::ReturnTag' },
  { name: 'return_rc', handler: 'Liquify::Tags::ReturnTag', comment: 'TODO: remove' },
  { name: 'rollback', handler: 'Liquify::Tags::RollbackTag' },
  { name: 'session', handler: 'Liquify::Tags::SessionTag' },
  { name: 'sign_in', handler: 'Liquify::Tags::SignInTag' },
  { name: 'sign_in_rc', handler: 'Liquify::Tags::SignInTag', comment: 'TODO: remove' },
  { name: 'spam_protection', handler: 'Liquify::Tags::SpamProtectionTag' },
  { name: 'theme_render_rc', handler: 'Liquify::Tags::ThemeRenderTag' },
  { name: 'transaction', handler: 'Liquify::Tags::TransactionTag' },
  { name: 'try', handler: 'Liquify::Tags::TryTag' },
  { name: 'try_rc', handler: 'Liquify::Tags::TryTag' },
  { name: 'yield', handler: 'Liquify::Tags::YieldTag' },
];
