import { describe, expect, it } from 'vitest';

import filtersJson from '../../platformos-check-docs-updater/data/filters.json';
import { AugmentedPlatformOSDocset } from './AugmentedPlatformOSDocset';
import { UNDOCUMENTED_FILTERS } from './undocumented-filters';
import type { PlatformOSDocset } from './types';

/** Only the two fields these tests read; the docs payload carries many more. */
type DocumentedFilter = { name: string; aliases?: string[] };

/**
 * TASK-20. This list is injected into the docset so `UnknownFilter` stays silent for
 * filters the official docs omit. That makes it dangerous in both directions, and it
 * had rotted badly in one of them: of 13 hand-typed entries, 12 did not exist on a real
 * instance. Each was a FALSE APPROVAL — `{{ 'a' | push: 1 }}` cleared the write gate
 * and then raised `Liquid::UndefinedFilter` at runtime.
 *
 * The list is now generated by `scripts/verify-undocumented-filters.mjs`, which keeps a
 * candidate only if a live instance renders it. These tests cannot re-probe an instance
 * (no credentials in CI, and a unit test must not depend on one), so they pin the two
 * properties that hold WITHOUT network access — the ones a hand-edit would break.
 */
const documented = filtersJson as DocumentedFilter[];
const documentedNames = new Set(documented.map((filter) => filter.name));
const documentedAliases = new Set(documented.flatMap((filter) => filter.aliases ?? []));

describe('Unit: UNDOCUMENTED_FILTERS', () => {
  it('is exactly the set proven to exist on a live instance', () => {
    // Pinned whole. Adding a name is a change to what the write gate accepts, so it
    // must be a deliberate edit HERE, made after re-running the generator — never a
    // quiet append to the array.
    expect([...UNDOCUMENTED_FILTERS]).toEqual(['find', 'find_index', 'h', 'has', 'sum', 'where']);
  });

  it('contains none of the 12 fictional filters that used to be hardcoded', () => {
    // Named individually rather than as a count: this is the regression, and each of
    // these is a distinct false approval if it ever returns.
    const fictional = [
      'debug',
      'distance_from',
      'encode_url_component',
      'excerpt',
      'format_code',
      'handle_from',
      'pad_spaces',
      'paragraphize',
      'push',
      'sentence',
      'unit',
      'weight',
    ];

    expect(fictional.filter((name) => UNDOCUMENTED_FILTERS.includes(name))).toEqual([]);
  });

  it('is genuinely UNdocumented — no entry duplicates the docs or an alias', () => {
    // The list exists only to cover what `filters.json` omits. An entry that the docs
    // already carry is dead weight, and one that duplicates an alias means
    // `expandAliases` already handles it.
    const redundant = UNDOCUMENTED_FILTERS.filter(
      (name) => documentedNames.has(name) || documentedAliases.has(name),
    );

    expect(redundant).toEqual([]);
  });

  it('reaches the docset, so `UnknownFilter` actually accepts these names', () => {
    // The list is only worth anything if it is wired in. Without this, deleting the
    // spread in `AugmentedPlatformOSDocset` would break every one of these filters and
    // no test above would notice.
    const bare: PlatformOSDocset = {
      filters: async () => [{ name: 'upcase' }],
      objects: async () => [],
      liquidDrops: async () => [],
      tags: async () => [],
      graphQL: async () => null,
    };

    return new AugmentedPlatformOSDocset(bare).filters().then((filters) => {
      const names = filters.map((filter) => filter.name);

      expect(UNDOCUMENTED_FILTERS.filter((name) => !names.includes(name))).toEqual([]);
      // ...and the official ones still come through alongside them.
      expect(names).toContain('upcase');
    });
  });
});
