// WARNING:
// This file was generated by "scripts/verify-undocumented-filters.mjs".
// Do not modify manually. Your changes will be overwritten.
//
// Every name below was PROVEN to exist by rendering it on a real platformOS instance,
// and proven absent from the docs API's `filters.json`. The comment on each line is
// what the instance actually returned.
//
// Instance:  https://fk-docs.ps-01-platformos.com
// Generated: 2026-08-01

/**
 * Filters that work in platformOS but are missing from the official docs.
 *
 * These are injected into {@link AugmentedPlatformOSDocset} so `UnknownFilter` does
 * not report working code as broken. Membership therefore has real consequences in
 * BOTH directions, which is why it is generated rather than typed:
 *
 *   - a name here that does NOT exist silences `UnknownFilter` for it, so broken code
 *     passes the write gate and raises at runtime (this happened: 12 of 13 hand-typed
 *     entries were fictional);
 *   - a real filter MISSING from here is reported as unknown, and because the MCP
 *     supervisor treats `UnknownFilter` as blocking, working code is refused.
 *
 * To change this list, edit the candidates in the generator and re-run it against an
 * instance. Do not add a name by hand — an unverified entry is how this rotted.
 */
export const UNDOCUMENTED_FILTERS: readonly string[] = [
  // rendered "{&quot;k&quot;:2}"
  'find',
  // rendered "1"
  'find_index',
  // rendered "abc"
  'h',
  // rendered "true"
  'has',
  // rendered "6"
  'sum',
  // rendered "[{&quot;k&quot;:1}]"
  'where',
];
