import { describe, expect, it } from 'vitest';

import { findDuplicateKeys } from './duplicate-keys';
import { PSYCH_KEY_IDENTITY } from './psych-key-identity';

/**
 * THE SOUNDNESS PROOF, over every pair of tokens Ruby was asked about.
 *
 * `duplicate-yaml-key/index.spec.ts` tests the check's behaviour on hand-picked shapes.
 * This file answers the question those cannot: across the whole corpus, does this
 * implementation ever claim a collision the PLATFORM does not have?
 *
 * That direction is the one that matters. A missed duplicate costs one silently-dropped
 * value. A false one tells an author to delete a key that is doing work — and round 5
 * found exactly that, because the identity was built from JS semantics (`typeof` +
 * `String()`), under which `1` and `1.0` are indistinguishable while Ruby keeps two keys.
 *
 * The oracle is generated by `scripts/verify-yaml-key-identity.mjs`, which asks Ruby
 * directly. Neither the YAML 1.1 spec nor either parser is the authority here: Psych does
 * not implement the spec's full boolean set (`y`/`n` stay strings), and npm's own 1.1 mode
 * disagrees with Psych about `y`, scientific notation, uppercase hex and sexagesimals.
 */

/** Tokens Ruby's safe loader refused to resolve — no identity to compare against. */
const RESOLVABLE = Object.entries(PSYCH_KEY_IDENTITY).filter(
  ([, identity]) => identity.klass !== 'ERROR' && identity.klass !== 'UNEXPECTED',
);

/** Whether Psych ends up with ONE key for these two tokens. */
const psychCollides = (a: string, b: string): boolean => {
  const left = PSYCH_KEY_IDENTITY[a];
  const right = PSYCH_KEY_IDENTITY[b];
  // Ruby Hash uses `eql?`, which is class-sensitive: 1 and 1.0 are `==` but not `eql?`.
  return left.klass === right.klass && left.value === right.value;
};

/** Whether THIS implementation reports a duplicate for a two-key document. */
const weReport = (a: string, b: string): boolean =>
  findDuplicateKeys(`${a}: x\n${b}: y\n`).length > 0;

describe('Sweep: key identity against Ruby Psych', () => {
  it('never reports a collision the platform does not have', async () => {
    // SOUNDNESS. Every ordered pair, so an asymmetry in the implementation shows up too.
    // A failure here is a FALSE POSITIVE on legal YAML, which is the expensive direction
    // and the reason this sweep exists rather than a handful of examples.
    const falsePositives: string[] = [];

    for (const [a] of RESOLVABLE) {
      for (const [b] of RESOLVABLE) {
        if (a === b) continue;
        if (weReport(a, b) && !psychCollides(a, b)) {
          falsePositives.push(
            `${a} + ${b} — Psych: ${PSYCH_KEY_IDENTITY[a].klass}(${PSYCH_KEY_IDENTITY[a].value}) vs ` +
              `${PSYCH_KEY_IDENTITY[b].klass}(${PSYCH_KEY_IDENTITY[b].value})`,
          );
        }
      }
    }

    expect(falsePositives).toEqual([]);
  });

  it('reports the collisions it can, and the ones it skips are named', async () => {
    // COMPLETENESS, pinned rather than maximised. Silence is safe but it is not free, so
    // a shrinking detection rate has to be visible in a diff instead of arriving quietly.
    //
    // Every entry below is a pair Psych collapses to one key that this implementation
    // deliberately does not compare — see UNCOMPARABLE in `duplicate-keys.ts`. Each is a
    // spelling where npm `yaml` and Psych resolve differently, so comparing it would risk
    // a false positive somewhere else in the corpus.
    const missed: string[] = [];

    for (const [a] of RESOLVABLE) {
      for (const [b] of RESOLVABLE) {
        if (a >= b) continue;
        if (psychCollides(a, b) && !weReport(a, b)) missed.push(`${a} + ${b}`);
      }
    }

    // ONE pair, across 3 540. The exclusion set is far cheaper than it looks, and this
    // number is the reason to state it rather than assume it: a first draft of this
    // assertion predicted six missed pairs, reasoning that everything in UNCOMPARABLE
    // must be a lost detection. Five of those six do not collide in Psych EITHER — an
    // uppercase `0X10` is the string "0X10" to Ruby, `1e3` is the string "1e3", `y` is
    // the string "y" — so declining to compare them costs nothing at all.
    //
    // Only the YAML 1.1 sexagesimal is a genuine trade: Psych reads `1:30` as 5400 and
    // npm as 90, so the two really do name one key and this cannot tell.
    expect(missed.sort()).toEqual(['1:30 + 5400']);
  });

  it('agrees with Psych that these DO collide', async () => {
    // The positive direction on the cases round 5 was about, asserted against the oracle
    // rather than against my reading of the YAML spec.
    expect(
      [
        ['yes', 'true'],
        ['on', 'true'],
        ['off', 'false'],
        ['014', '12'],
        ['0x10', '16'],
        ['+1', '1'],
        ['null', '~'],
        ['TRUE', 'true'],
      ].map(([a, b]) => [a, b, psychCollides(a, b), weReport(a, b)]),
    ).toEqual([
      ['yes', 'true', true, true],
      ['on', 'true', true, true],
      ['off', 'false', true, true],
      ['014', '12', true, true],
      ['0x10', '16', true, true],
      ['+1', '1', true, true],
      ['null', '~', true, true],
      ['TRUE', 'true', true, true],
    ]);
  });

  it('agrees with Psych that these do NOT collide', async () => {
    expect(
      [
        ['1', '1.0'],
        ['1', '"1"'],
        ['true', "'true'"],
        ['yes', '"yes"'],
        ['on', 'off'],
        ['null', '"null"'],
        // `nil` is not a YAML null in either parser — it is the string "nil".
        ['nil', 'null'],
      ].map(([a, b]) => [a, b, psychCollides(a, b), weReport(a, b)]),
    ).toEqual([
      ['1', '1.0', false, false],
      ['1', '"1"', false, false],
      ['true', "'true'", false, false],
      ['yes', '"yes"', false, false],
      ['on', 'off', false, false],
      ['null', '"null"', false, false],
      ['nil', 'null', false, false],
    ]);
  });

  it('covers the corpus it claims to, so the sweep cannot silently shrink', async () => {
    const total = Object.keys(PSYCH_KEY_IDENTITY).length;
    const refused = total - RESOLVABLE.length;

    expect({ total, refused, pairsSwept: RESOLVABLE.length * (RESOLVABLE.length - 1) }).toEqual({
      total: 61,
      // Ruby's safe loader refuses to build a Date; that is a fact about the loader, not
      // about key identity, so timestamps are excluded rather than guessed at.
      refused: 1,
      pairsSwept: 3540,
    });
  });
});
