// WARNING:
// This file was generated by "scripts/verify-yaml-key-identity.mjs".
// Do not modify manually. Your changes will be overwritten.
//
// How Ruby Psych — the platform's YAML parser — resolves each scalar token when it is
// used as a mapping key. Two keys collide on the platform iff their class AND value
// match, because that is what Ruby's Hash uses (`eql?`, not `==`).
//
// Measured with: ruby 4.0.6, psych 5.3.1
// Generated: 2026-08-02

/** What Psych resolved one key token to. */
export interface PsychKeyIdentity {
  /** Ruby class name, e.g. `Integer`, `Float`, `String`, `TrueClass`, `NilClass`. */
  klass: string;
  /** `inspect` output, so `1` and `1.0` are distinguishable and quoting is visible. */
  value: string;
}

/**
 * Every probed token, keyed by its SOURCE TEXT.
 *
 * Consumed by `duplicate-keys.spec.ts`, which groups these into equivalence classes and
 * asserts the check agrees with every one — both where it must report a duplicate and
 * where it must stay silent.
 *
 * `klass: 'ERROR'` means Ruby's safe loader refused the token (timestamps), which is a
 * fact about the loader rather than about key identity; the spec treats those as
 * uncomparable rather than pretending to know.
 */
export const PSYCH_KEY_IDENTITY: Readonly<Record<string, PsychKeyIdentity>> = {
  '0': { klass: 'Integer', value: '0' },
  '1': { klass: 'Integer', value: '1' },
  '12': { klass: 'Integer', value: '12' },
  '16': { klass: 'Integer', value: '16' },
  '90': { klass: 'Integer', value: '90' },
  '1000': { klass: 'Integer', value: '1000' },
  '5400': { klass: 'Integer', value: '5400' },
  true: { klass: 'TrueClass', value: 'true' },
  True: { klass: 'TrueClass', value: 'true' },
  TRUE: { klass: 'TrueClass', value: 'true' },
  false: { klass: 'FalseClass', value: 'false' },
  False: { klass: 'FalseClass', value: 'false' },
  FALSE: { klass: 'FalseClass', value: 'false' },
  yes: { klass: 'TrueClass', value: 'true' },
  Yes: { klass: 'TrueClass', value: 'true' },
  YES: { klass: 'TrueClass', value: 'true' },
  no: { klass: 'FalseClass', value: 'false' },
  No: { klass: 'FalseClass', value: 'false' },
  NO: { klass: 'FalseClass', value: 'false' },
  on: { klass: 'TrueClass', value: 'true' },
  On: { klass: 'TrueClass', value: 'true' },
  ON: { klass: 'TrueClass', value: 'true' },
  off: { klass: 'FalseClass', value: 'false' },
  Off: { klass: 'FalseClass', value: 'false' },
  OFF: { klass: 'FalseClass', value: 'false' },
  y: { klass: 'String', value: '"y"' },
  Y: { klass: 'String', value: '"Y"' },
  n: { klass: 'String', value: '"n"' },
  N: { klass: 'String', value: '"N"' },
  '+1': { klass: 'Integer', value: '1' },
  '-1': { klass: 'Integer', value: '-1' },
  '0x10': { klass: 'Integer', value: '16' },
  '0X10': { klass: 'String', value: '"0X10"' },
  '014': { klass: 'Integer', value: '12' },
  '0o14': { klass: 'String', value: '"0o14"' },
  '1_000': { klass: 'Integer', value: '1000' },
  '1.0': { klass: 'Float', value: '1.0' },
  '1.00': { klass: 'Float', value: '1.0' },
  '-1.0': { klass: 'Float', value: '-1.0' },
  '1e3': { klass: 'String', value: '"1e3"' },
  '1.5': { klass: 'Float', value: '1.5' },
  '.inf': { klass: 'Float', value: 'Infinity' },
  '-.inf': { klass: 'Float', value: '-Infinity' },
  '.nan': { klass: 'Float', value: 'NaN' },
  '1:30': { klass: 'Integer', value: '5400' },
  null: { klass: 'NilClass', value: 'nil' },
  Null: { klass: 'NilClass', value: 'nil' },
  NULL: { klass: 'NilClass', value: 'nil' },
  '~': { klass: 'NilClass', value: 'nil' },
  nil: { klass: 'String', value: '"nil"' },
  "'true'": { klass: 'String', value: '"true"' },
  "'yes'": { klass: 'String', value: '"yes"' },
  "'1'": { klass: 'String', value: '"1"' },
  '"1"': { klass: 'String', value: '"1"' },
  '"yes"': { klass: 'String', value: '"yes"' },
  '"null"': { klass: 'String', value: '"null"' },
  '2026-01-01': { klass: 'ERROR', value: 'Psych::DisallowedClass' },
  abc: { klass: 'String', value: '"abc"' },
  'a b': { klass: 'String', value: '"a b"' },
  title: { klass: 'String', value: '"title"' },
  en: { klass: 'String', value: '"en"' },
};
