// WARNING:
// This file was generated by "scripts/verify-yaml-key-identity.mjs".
// Do not modify manually. Your changes will be overwritten.
//
// How Ruby Psych — the platform's YAML parser — resolves each scalar token when it is
// used as a mapping key. Two keys collide on the platform iff their class AND value
// match, because that is what Ruby's Hash uses (`eql?`, not `==`).
//
// Measured with: ruby 4.0.6, psych 5.3.1
// Generated: 2026-08-03

/** What Psych resolved one key token to. */
export interface PsychKeyIdentity {
  /** Ruby class name, e.g. `Integer`, `Float`, `String`, `TrueClass`, `NilClass`. */
  klass: string;
  /** `inspect` output, so `1` and `1.0` are distinguishable and quoting is visible. */
  value: string;
  /**
   * MEASURED equivalence class. Two tokens share a group iff Ruby collapses a document that
   * uses both as keys into a single entry — which is the question the duplicate-key check
   * has to answer, asked directly rather than derived from `klass`/`value`.
   *
   * Absent when Ruby refused the token, since an unresolvable key has no class to be in.
   */
  group?: number;
}

/**
 * Every probed token, keyed by its SOURCE TEXT.
 *
 * Consumed by `duplicate-keys.spec.ts`, which groups these into equivalence classes and
 * asserts the check agrees with every one — both where it must report a duplicate and
 * where it must stay silent.
 *
 * `klass: 'ERROR'` means Ruby's safe loader refused the token (timestamps), which is a
 * fact about the loader rather than about key identity; the spec treats those as
 * uncomparable rather than pretending to know.
 */
export const PSYCH_KEY_IDENTITY: Readonly<Record<string, PsychKeyIdentity>> = {
  '0': { klass: 'Integer', value: '0', group: 6 },
  '1': { klass: 'Integer', value: '1', group: 7 },
  '12': { klass: 'Integer', value: '12', group: 8 },
  '16': { klass: 'Integer', value: '16', group: 9 },
  '90': { klass: 'Integer', value: '90', group: 23 },
  '1000': { klass: 'Integer', value: '1000', group: 10 },
  '5400': { klass: 'Integer', value: '5400', group: 11 },
  true: { klass: 'TrueClass', value: 'true', group: 0 },
  True: { klass: 'TrueClass', value: 'true', group: 0 },
  TRUE: { klass: 'TrueClass', value: 'true', group: 0 },
  false: { klass: 'FalseClass', value: 'false', group: 1 },
  False: { klass: 'FalseClass', value: 'false', group: 1 },
  FALSE: { klass: 'FalseClass', value: 'false', group: 1 },
  yes: { klass: 'TrueClass', value: 'true', group: 0 },
  Yes: { klass: 'TrueClass', value: 'true', group: 0 },
  YES: { klass: 'TrueClass', value: 'true', group: 0 },
  no: { klass: 'FalseClass', value: 'false', group: 1 },
  No: { klass: 'FalseClass', value: 'false', group: 1 },
  NO: { klass: 'FalseClass', value: 'false', group: 1 },
  on: { klass: 'TrueClass', value: 'true', group: 0 },
  On: { klass: 'TrueClass', value: 'true', group: 0 },
  ON: { klass: 'TrueClass', value: 'true', group: 0 },
  off: { klass: 'FalseClass', value: 'false', group: 1 },
  Off: { klass: 'FalseClass', value: 'false', group: 1 },
  OFF: { klass: 'FalseClass', value: 'false', group: 1 },
  y: { klass: 'String', value: '"y"', group: 2 },
  Y: { klass: 'String', value: '"Y"', group: 3 },
  n: { klass: 'String', value: '"n"', group: 4 },
  N: { klass: 'String', value: '"N"', group: 5 },
  '+1': { klass: 'Integer', value: '1', group: 7 },
  '-1': { klass: 'Integer', value: '-1', group: 12 },
  '0x10': { klass: 'Integer', value: '16', group: 9 },
  '0X10': { klass: 'String', value: '"0X10"', group: 13 },
  '014': { klass: 'Integer', value: '12', group: 8 },
  '0o14': { klass: 'String', value: '"0o14"', group: 14 },
  '1_000': { klass: 'Integer', value: '1000', group: 10 },
  '1.0': { klass: 'Float', value: '1.0', group: 15 },
  '1.00': { klass: 'Float', value: '1.0', group: 15 },
  '-1.0': { klass: 'Float', value: '-1.0', group: 16 },
  '1e3': { klass: 'String', value: '"1e3"', group: 17 },
  '1.5': { klass: 'Float', value: '1.5', group: 18 },
  '.inf': { klass: 'Float', value: 'Infinity', group: 19 },
  '-.inf': { klass: 'Float', value: '-Infinity', group: 20 },
  '.nan': { klass: 'Float', value: 'NaN', group: 21 },
  '-0.0': { klass: 'Float', value: '-0.0', group: 22 },
  '0.0': { klass: 'Float', value: '0.0', group: 22 },
  '+0.0': { klass: 'Float', value: '0.0', group: 22 },
  TrUe: { klass: 'TrueClass', value: 'true', group: 0 },
  oN: { klass: 'TrueClass', value: 'true', group: 0 },
  yEs: { klass: 'TrueClass', value: 'true', group: 0 },
  '.Inf': { klass: 'Float', value: 'Infinity', group: 19 },
  '.NaN': { klass: 'Float', value: 'NaN', group: 21 },
  '1:30': { klass: 'Integer', value: '5400', group: 11 },
  null: { klass: 'NilClass', value: 'nil', group: 24 },
  Null: { klass: 'NilClass', value: 'nil', group: 24 },
  NULL: { klass: 'NilClass', value: 'nil', group: 24 },
  '~': { klass: 'NilClass', value: 'nil', group: 24 },
  nil: { klass: 'String', value: '"nil"', group: 25 },
  "'true'": { klass: 'String', value: '"true"', group: 26 },
  "'yes'": { klass: 'String', value: '"yes"', group: 27 },
  "'1'": { klass: 'String', value: '"1"', group: 28 },
  '"1"': { klass: 'String', value: '"1"', group: 28 },
  '"yes"': { klass: 'String', value: '"yes"', group: 27 },
  '"null"': { klass: 'String', value: '"null"', group: 29 },
  '".inf"': { klass: 'String', value: '".inf"', group: 30 },
  '"0X10"': { klass: 'String', value: '"0X10"', group: 13 },
  '"1e3"': { klass: 'String', value: '"1e3"', group: 17 },
  '"y"': { klass: 'String', value: '"y"', group: 2 },
  '"1:30"': { klass: 'String', value: '"1:30"', group: 31 },
  '"TrUe"': { klass: 'String', value: '"TrUe"', group: 32 },
  '2026-01-01': { klass: 'ERROR', value: 'Psych::DisallowedClass' },
  abc: { klass: 'String', value: '"abc"', group: 33 },
  'a b': { klass: 'String', value: '"a b"', group: 34 },
  title: { klass: 'String', value: '"title"', group: 35 },
  en: { klass: 'String', value: '"en"', group: 36 },
};
