import yaml from 'js-yaml';
import { AbstractFileSystem, FileType } from '../AbstractFileSystem';
import { getAppPaths, getModulePaths, parseModulePrefix, PlatformOSFileType } from '../path-utils';
import { URI, Utils } from 'vscode-uri';

export type DocumentType =
  | 'function'
  | 'render'
  | 'include'
  | 'background'
  | 'graphql'
  | 'asset'
  | 'layout'
  | 'theme_render_rc';

/**
 * Load theme_search_paths from app/config.yml.
 * Returns null if the file doesn't exist, is malformed, or has no valid theme_search_paths.
 * Results should be cached per root URI.
 */
export async function loadSearchPaths(
  fs: { readFile(uri: string): Promise<string> },
  rootUri: URI,
): Promise<string[] | null> {
  try {
    const configUri = Utils.joinPath(rootUri, 'app/config.yml').toString();
    const content = await fs.readFile(configUri);
    const config = yaml.load(content) as Record<string, unknown> | null;
    const paths = config?.theme_search_paths;
    if (Array.isArray(paths) && paths.length > 0) {
      return paths.map(String);
    }
    return null;
  } catch {
    return null;
  }
}

/** Maximum number of concrete paths generated by a single dynamic search-path expansion. */
const MAX_DYNAMIC_PATH_EXPANSIONS = 100;

export class DocumentsLocator {
  constructor(private readonly fs: AbstractFileSystem) {}

  private async isFile(path: string): Promise<boolean> {
    try {
      return (await this.fs.stat(path)).type === FileType.File;
    } catch {
      return false;
    }
  }

  private getSearchPaths(
    type: 'partial' | 'graphql' | 'asset' | 'layout',
    moduleName?: string,
  ): string[] {
    const fileType: PlatformOSFileType = {
      partial: PlatformOSFileType.Partial,
      graphql: PlatformOSFileType.GraphQL,
      asset: PlatformOSFileType.Asset,
      layout: PlatformOSFileType.Layout,
    }[type];

    return moduleName ? getModulePaths(fileType, moduleName) : getAppPaths(fileType);
  }

  /**
   * Candidate filename extensions to probe for a physical file type, in priority
   * order. Layouts exist as either `.html.liquid` (legacy) or `.liquid`, so both
   * are tried (`.html.liquid` first). Assets carry their own extension in the
   * name, so the candidate is the name itself (empty suffix).
   */
  private static readonly EXTENSIONS: Record<'partial' | 'graphql' | 'asset' | 'layout', string[]> =
    {
      partial: ['.liquid'],
      graphql: ['.graphql'],
      layout: ['.html.liquid', '.liquid'],
      asset: [''],
    };

  private async locateFile(
    rootUri: URI,
    fileName: string,
    type: 'partial' | 'graphql' | 'asset' | 'layout',
  ): Promise<string | undefined> {
    const parsed = parseModulePrefix(fileName);
    const searchPaths = this.getSearchPaths(type, parsed.isModule ? parsed.moduleName : undefined);
    const candidates = DocumentsLocator.EXTENSIONS[type].map((ext) => parsed.key + ext);

    for (const basePath of searchPaths) {
      for (const candidate of candidates) {
        const uri = Utils.joinPath(rootUri, basePath, candidate).toString();

        if (await this.isFile(uri)) {
          return uri;
        }
      }
    }

    return undefined;
  }

  private async listFiles(
    rootUri: URI,
    filePrefix: string,
    type: 'partial' | 'graphql' | 'asset',
  ): Promise<string[]> {
    const parsed = parseModulePrefix(filePrefix);
    const searchPaths = this.getSearchPaths(type, parsed.isModule ? parsed.moduleName : undefined);

    const results = new Set<string>();

    const matchesType = (name: string): boolean => {
      switch (type) {
        case 'partial':
          return name.endsWith('.liquid');
        case 'graphql':
          return name.endsWith('.graphql');
        case 'asset':
          return true;
      }
    };

    const walk = async (basePath: string, dirUri: URI): Promise<void> => {
      let entries: [string, FileType][];
      try {
        entries = await this.fs.readDirectory(dirUri.toString());
      } catch {
        return;
      }

      for (const [name, fileType] of entries) {
        if (fileType === FileType.Directory) {
          await walk(basePath, URI.parse(name));
          continue;
        }

        if (fileType !== FileType.File) continue;
        if (!matchesType(name)) continue;

        const parsedName = name.slice(basePath.length);
        if (!parsedName.startsWith('/' + parsed.key)) continue;
        let result = parsedName.slice(parsed.key.length);

        if ((parsed.key.endsWith('/') || parsed.key === '') && result.startsWith('/'))
          result = result.slice(1);

        if (type !== 'asset') {
          const index = result.lastIndexOf('.');
          result = index === -1 ? result : result.slice(0, index);
        }
        results.add(result);
      }
    };

    for (const basePath of searchPaths) {
      const baseUri = Utils.joinPath(rootUri, basePath);
      await walk(baseUri.toString(), baseUri);
    }

    return Array.from(results).sort((a, b) => a.localeCompare(b));
  }

  private static readonly LIQUID_EXPRESSION_RE = /\{\{.*?\}\}/;

  private async listSubdirectoryNames(dirUri: string): Promise<string[]> {
    try {
      const entries = await this.fs.readDirectory(dirUri);
      return entries
        .filter(([, type]) => type === FileType.Directory)
        .map(([name]) => {
          const lastSlash = name.lastIndexOf('/');
          return lastSlash === -1 ? name : name.slice(lastSlash + 1);
        })
        .filter((name) => name.length > 0);
    } catch {
      return [];
    }
  }

  private expandedPathsCache = new Map<string, Promise<string[]>>();

  clearExpandedPathsCache(): void {
    this.expandedPathsCache.clear();
  }

  /**
   * Expand a search path that may contain {{ ... }} Liquid expressions into
   * concrete directory prefixes by enumerating subdirectories at each dynamic
   * segment. Static segments pass through unchanged.
   *
   * Results are cached per (rootUri, searchPath) and capped at
   * MAX_DYNAMIC_PATH_EXPANSIONS entries per dynamic segment.
   */
  private async expandDynamicPath(rootUri: URI, searchPath: string): Promise<string[]> {
    const segments = searchPath.split('/');
    const basePaths = this.getSearchPaths('partial');
    let prefixes = [''];

    for (const segment of segments) {
      if (!DocumentsLocator.LIQUID_EXPRESSION_RE.test(segment)) {
        prefixes = prefixes.map((p) => (p ? `${p}/${segment}` : segment));
        continue;
      }

      const nextPrefixes: string[] = [];
      for (const prefix of prefixes) {
        const subdirs = new Set<string>();
        for (const base of basePaths) {
          const dirUri = prefix
            ? Utils.joinPath(rootUri, base, prefix).toString()
            : Utils.joinPath(rootUri, base).toString();
          for (const name of await this.listSubdirectoryNames(dirUri)) {
            subdirs.add(name);
          }
        }
        for (const sub of subdirs) {
          nextPrefixes.push(prefix ? `${prefix}/${sub}` : sub);
          if (nextPrefixes.length >= MAX_DYNAMIC_PATH_EXPANSIONS) break;
        }
        if (nextPrefixes.length >= MAX_DYNAMIC_PATH_EXPANSIONS) break;
      }
      prefixes = nextPrefixes;
    }

    return prefixes;
  }

  /**
   * Resolve a search path (static, dynamic, or empty) into concrete prefix
   * strings. Cached for dynamic paths.
   */
  private async resolveSearchPath(rootUri: URI, searchPath: string): Promise<string[]> {
    if (searchPath === '') return [''];
    if (!DocumentsLocator.LIQUID_EXPRESSION_RE.test(searchPath)) return [searchPath];

    const cacheKey = `${rootUri.toString()}:${searchPath}`;
    if (!this.expandedPathsCache.has(cacheKey)) {
      this.expandedPathsCache.set(cacheKey, this.expandDynamicPath(rootUri, searchPath));
    }
    return this.expandedPathsCache.get(cacheKey)!;
  }

  /**
   * Locate a partial using theme search paths (for theme_render_rc).
   *
   * Tries each search path prefix in priority order, then falls back to the
   * unprefixed name (unless '' was already in the list, meaning the default
   * position was explicitly placed).
   */
  async locateWithSearchPaths(
    rootUri: URI,
    fileName: string,
    themeSearchPaths: string[],
  ): Promise<string | undefined> {
    for (const searchPath of themeSearchPaths) {
      for (const prefix of await this.resolveSearchPath(rootUri, searchPath)) {
        const candidate = prefix ? `${prefix}/${fileName}` : fileName;
        const result = await this.locateFile(rootUri, candidate, 'partial');
        if (result) return result;
      }
    }

    if (!themeSearchPaths.includes('')) {
      return this.locateFile(rootUri, fileName, 'partial');
    }

    return undefined;
  }

  /**
   * Returns the canonical URI where `fileName` would live — used as a
   * go-to-definition fallback when the file doesn't exist yet.
   * Returns undefined for theme_render_rc (ambiguous search path) and asset.
   */
  locateDefault(rootUri: URI, nodeName: DocumentType, fileName: string): string | undefined {
    const parsed = parseModulePrefix(fileName);

    let basePath: string;
    let ext: string;

    switch (nodeName) {
      case 'render':
      case 'include':
      case 'background':
        basePath = parsed.isModule
          ? `modules/${parsed.moduleName}/public/views/partials`
          : 'app/views/partials';
        ext = '.liquid';
        break;
      case 'function':
        basePath = parsed.isModule ? `modules/${parsed.moduleName}/public/lib` : 'app/lib';
        ext = '.liquid';
        break;
      case 'graphql':
        basePath = parsed.isModule ? `modules/${parsed.moduleName}/public/graphql` : 'app/graphql';
        ext = '.graphql';
        break;
      case 'layout':
        // Canonical creation path uses the modern `.liquid` extension (not the
        // legacy `.html.liquid`), consistent with how the other types default.
        basePath = parsed.isModule
          ? `modules/${parsed.moduleName}/public/views/layouts`
          : 'app/views/layouts';
        ext = '.liquid';
        break;
      case 'theme_render_rc': // ambiguous — multiple search paths, no single canonical location
      case 'asset': // no canonical creation path
        return undefined;
      default:
        return undefined;
    }

    return Utils.joinPath(rootUri, basePath, parsed.key + ext).toString();
  }

  /**
   * Resolves `fileName` to a filesystem URI (if the file exists), or falls
   * back to the canonical default URI from `locateDefault`.
   */
  async locateOrDefault(
    rootUri: URI,
    nodeName: DocumentType,
    fileName: string,
    themeSearchPaths?: string[] | null,
  ): Promise<string | undefined> {
    return (
      (await this.locate(rootUri, nodeName, fileName, themeSearchPaths)) ??
      this.locateDefault(rootUri, nodeName, fileName)
    );
  }

  async locate(
    rootUri: URI,
    nodeName: DocumentType,
    fileName: string,
    themeSearchPaths?: string[] | null,
  ): Promise<string | undefined> {
    switch (nodeName) {
      case 'render':
      case 'include':
      case 'background':
      case 'function':
        return this.locateFile(rootUri, fileName, 'partial');

      case 'theme_render_rc':
        return themeSearchPaths
          ? this.locateWithSearchPaths(rootUri, fileName, themeSearchPaths)
          : this.locateFile(rootUri, fileName, 'partial');

      case 'graphql':
        return this.locateFile(rootUri, fileName, 'graphql');

      case 'asset':
        return this.locateFile(rootUri, fileName, 'asset');

      case 'layout':
        return this.locateFile(rootUri, fileName, 'layout');

      default:
        return undefined;
    }
  }

  async list(rootUri: URI, nodeName: string | undefined, filePrefix: string): Promise<string[]> {
    switch (nodeName) {
      case 'function':
      case 'render':
      case 'include':
      case 'background':
      case 'theme_render_rc':
        return this.listFiles(rootUri, filePrefix, 'partial');

      case 'graphql':
        return this.listFiles(rootUri, filePrefix, 'graphql');

      case 'asset':
        return this.listFiles(rootUri, filePrefix, 'asset');

      default:
        return [];
    }
  }
}
