import { describe, expect, it } from 'vitest';

import { InvalidHashAssignTarget } from './index';
import {
  FILTER_RETURN_TYPE_ORACLE,
  HASH_RETURN_TYPE_FILTERS,
  UNTYPED_RETURN_TYPE_SPELLINGS,
  type FilterReturnTypeMeasurement,
  type RuntimeOutcome,
} from './filter-return-type-oracle';
import filtersJson from '../../../../platformos-check-docs-updater/data/filters.json';
import { runLiquidCheck } from '../../test';
import type { PlatformOSDocset } from '../../types';

/**
 * THE SWEEP. Every filter whose docset `return_type` makes this check willing to report,
 * driven through `assign` then `hash_assign` with both kinds of subscript, and settled
 * against what a live instance actually did.
 *
 * WHY ALL OF THEM AND NOT A SAMPLE. 163 filter names reach a reporting type, and this
 * check BLOCKS: a single wrong `return_type` among them is an unappealable refusal of
 * working code. Checking a dozen and finding them all correct says nothing about the
 * other 151, because sampling an accepting population cannot find an over-accepting
 * member. That is the same structural blindness that let twelve fictional names survive
 * in `undocumentedFilters` until a full sweep replaced the spot checks, and it is why
 * this file exists rather than a few more hand-picked cases.
 *
 * 163, NOT 138. `filters.json` holds 140 reporting rows over 138 distinct names, but
 * `AugmentedPlatformOSDocset.expandAliases` re-emits every entry under each of its
 * aliases, `return_type` included — so `to_json`, `t`, `select`, `sort_by`,
 * `map_attributes` and 20 more names the docset never lists as filters are all names this
 * check will refuse a write for. Sweeping the raw docset would have covered 138 and
 * reported full coverage while missing 25 of them, which is the same shape of mistake as
 * sampling, one level up.
 *
 * THE MEASUREMENTS ARE NOT MADE HERE. `filter-return-type-oracle.ts` is generated by
 * `scripts/verify-filter-return-types.mjs` against a real instance and committed; this
 * file is hermetic and runs in CI. The two halves are what make the sweep bite:
 *
 *   - the ORACLE says what the runtime does
 *   - this SPEC drives the real check over the real `filters.json`
 *
 * so a docset update that changes a `return_type` fails here instead of quietly changing
 * what the server refuses to write. When it does fail, re-run the generator: the fix is
 * either a corrected mapping in the check or a corrected row in the docset, and the
 * failure names which filter to look at.
 *
 * THE RESULT OF THE FIRST FULL SWEEP was that the docset is right about every one of the
 * 163, aliases included. That is a negative result, and it is worth having: the largest
 * unexamined surface in this check turned out to hold no over-accepting entry, and it is
 * now pinned rather than re-argued.
 */

/** Docset `return_type.type` spellings the check will act on — mirrors DOCSET_RETURN_TYPES. */
const REPORTING_SPELLINGS = ['string', 'array', 'number', 'boolean'];

interface DocsetFilter {
  name: string;
  aliases?: string[];
  return_type?: Array<{ type: string }>;
}

/**
 * The reporting filters as the CHECK sees them.
 *
 * Mirrors `AugmentedPlatformOSDocset.filters()`: official entries, then one copy per
 * alias carrying the SAME return type. Order matters — the check builds a Map keyed by
 * name, so the last entry wins, which is also why `map` and `split` appearing twice in
 * `filters.json` collapses rather than conflicts.
 *
 * The undocumented filters the augmentation appends carry no `return_type` at all, so
 * they resolve to `untyped` and report nothing; they are covered by
 * `undocumented-filters.spec.ts` and are not part of this population.
 */
const reportingFromDocset = (): Map<string, string> => {
  const official = filtersJson as DocsetFilter[];
  const aliases = official.flatMap((filter) =>
    (filter.aliases ?? []).map((alias) => ({ ...filter, name: alias })),
  );

  const byName = new Map<string, string>();
  for (const filter of [...official, ...aliases]) {
    const returnType = filter.return_type;
    if (!returnType || returnType.length !== 1) continue;
    if (!REPORTING_SPELLINGS.includes(returnType[0].type)) continue;
    byName.set(filter.name, returnType[0].type);
  }
  return byName;
};

/**
 * The real docset, handed to the check exactly as the runtime would.
 *
 * Deliberately NOT a hand-written mock. A mock proves the check can read a return type;
 * only the shipped data proves it reads THIS return type, for all 163, which is the
 * whole question. It is passed RAW: `runLiquidCheck` goes through the engine's own
 * `check()`, which wraps it in `AugmentedPlatformOSDocset` — so the aliases are expanded
 * by the real code path rather than by anything this file arranges.
 */
const docset = {
  async filters() {
    return filtersJson;
  },
  async objects() {
    return [];
  },
  async tags() {
    return [];
  },
  async graphQL() {
    return null;
  },
} as unknown as PlatformOSDocset;

/**
 * Whether the check reports on `{% assign x = 'a' | <name> %}{% hash_assign x[…] %}`.
 *
 * THE ARGUMENTS ARE IRRELEVANT AND THAT IS THE POINT: the check reads the LAST filter's
 * name and looks its return type up in the docset. It never evaluates arguments, so
 * `'a' | ecdh_compute` exercises it identically to the fully-formed call the generator
 * had to build for the runtime — and no key material has to live in this repository.
 *
 * BOTH SHAPES ARE RUN because this check has already had one boundary defect that only
 * one of them could see: a range starts at the defining tag's end offset, and Liquid tags
 * may abut with nothing between them, so `{% assign %}{% hash_assign %}` and the same
 * pair split by a newline took different paths. A sweep that used one shape would have
 * had a blind spot exactly where the last bug was.
 */
const reportsFor = async (name: string, subscript: string): Promise<boolean> => {
  const assign = `{% assign x = 'a' | ${name} %}`;
  const hashAssign = `{% hash_assign x[${subscript}] = 'v' %}`;

  const shapes = await Promise.all(
    [`${assign}${hashAssign}`, `${assign}\n${hashAssign}`].map((source) =>
      runLiquidCheck(InvalidHashAssignTarget, source, 'file.liquid', {
        platformosDocset: docset,
      }),
    ),
  );

  const [adjacent, newline] = shapes.map((offenses) => offenses.length > 0);
  if (adjacent !== newline) {
    throw new Error(
      `${name}[${subscript}]: adjacent and newline-separated shapes disagree ` +
        `(adjacent=${adjacent}, newline=${newline}). The tags abut at a single offset in ` +
        `the first shape; see findVariableType's inclusive start bound.`,
    );
  }
  return adjacent;
};

/**
 * What the runtime did, for a row the transport could not carry an answer for.
 *
 * THREE FILTERS ARE UNMEASURABLE DIRECTLY, and the reason is a property of the probe
 * rather than of the runtime: `ecdh_compute`, `gzip_compress` and `hkdf` all return
 * binary, the runtime's complaint quotes the offending value back, and the resulting
 * response is an HTTP 406 that carries no body at all.
 *
 * They are settled by COMPOSITION rather than assumption, and only where the table
 * itself supports it: every one measured `type_of` as `String`, and every OTHER row that
 * measured `String` was measured raising for both subscripts. So the outcome is read off
 * the rows that share the runtime type — and if those rows ever disagree among
 * themselves, this throws instead of picking one. An inference the data stops supporting
 * must fail loudly, not silently become a guess.
 */
const settledOutcome = (
  row: FilterReturnTypeMeasurement,
  bucket: 'keyAssign' | 'indexAssign',
): RuntimeOutcome => {
  if (row[bucket] !== 'unmeasured') return row[bucket];

  const peers = new Set(
    FILTER_RETURN_TYPE_ORACLE.filter(
      (other) =>
        other.name !== row.name &&
        other.runtimeType === row.runtimeType &&
        other[bucket] !== 'unmeasured',
    ).map((other) => other[bucket]),
  );

  if (peers.size !== 1) {
    throw new Error(
      `${row.name}.${bucket} is unmeasured and cannot be settled: rows with runtimeType ` +
        `"${row.runtimeType}" report ${peers.size === 0 ? 'nothing' : [...peers].join('/')}. ` +
        `Re-run scripts/verify-filter-return-types.mjs or measure this filter directly.`,
    );
  }
  return [...peers][0];
};

describe('Sweep: docset return types vs the runtime, for every reporting filter', () => {
  it('covers exactly the filters the shipped docset makes reportable', async () => {
    // THE TRIPWIRE. The oracle is measured data with a date on it; the docset ships
    // separately and can gain, lose or retype a filter at any time. If those two sets
    // ever differ, every assertion below is silently sweeping the wrong population — so
    // this runs first and names the difference.
    expect([...reportingFromDocset().keys()].sort()).toEqual(
      FILTER_RETURN_TYPE_ORACLE.map((row) => row.name).sort(),
    );
  });

  it('sweeps the alias names too, which appear nowhere in filters.json as filters', async () => {
    // NAMED EXPLICITLY BECAUSE THIS WAS ALMOST MISSED. The sweep was built over
    // `filters.json` and looked complete at 138 names; the check actually sees 163,
    // because `expandAliases` re-emits every entry under each alias with the parent's
    // `return_type` attached. Those 25 names are reportable, blocking, and absent from
    // the docset's own filter list — so a sweep that reads only the docset covers them
    // by accident or not at all.
    //
    // Pinned as a list rather than a count: a new alias on a reporting filter is a new
    // name this check will refuse writes for, and it should arrive as a failure that
    // says which one.
    expect(
      FILTER_RETURN_TYPE_ORACLE.filter((row) => row.aliasOf).map(
        (row) => `${row.name} < ${row.aliasOf}`,
      ),
    ).toEqual([
      'add_to_array < array_add',
      'any < array_any',
      'compact < array_compact',
      'date_before < is_date_before',
      'flatten < array_flatten',
      'in_groups_of < array_in_groups_of',
      'intersection < array_intersect',
      'is_included_in_array < array_include',
      'jwe_encode_rc < jwe_encode',
      'limit < array_limit',
      'map_attributes < array_map',
      'markdownify < markdown',
      'prepend_to_array < array_prepend',
      'reject < array_reject',
      'rotate < array_rotate',
      'select < array_select',
      'shuffle_array < array_shuffle',
      'sort_by < array_sort_by',
      'subtract_array < array_subtract',
      'sum_array < array_sum',
      't < translate',
      't_escape < translate_escape',
      'to_json < json',
      'to_xml_rc < to_xml',
      'www_form_encode_rc < www_form_encode',
    ]);
  });

  it('records the same return type the shipped docset does, for every filter', async () => {
    // The other half of the tripwire: same names, same spellings. A docset row retyped
    // from `array` to `string` keeps the name and changes what the check refuses.
    const docsetTypes = reportingFromDocset();
    expect(
      FILTER_RETURN_TYPE_ORACLE.map((row) => ({ name: row.name, docset: row.docset })),
    ).toEqual(
      FILTER_RETURN_TYPE_ORACLE.map((row) => ({
        name: row.name,
        docset: docsetTypes.get(row.name),
      })),
    );
  });

  it('never refuses a hash_assign the runtime accepts, and never accepts one it refuses', async () => {
    // THE SWEEP ITSELF, in the only form that matters: the check's verdict against the
    // runtime's, for all 138 filters and both subscripts.
    //
    // Asserted as an empty list of disagreements rather than 276 separate expectations,
    // so a failure names every filter at once — a docset regression usually moves a
    // whole spelling, not one entry, and seeing "31 array filters disagree" is a
    // different diagnosis from seeing the first one fail.
    const disagreements: Array<{
      filter: string;
      subscript: string;
      checkReports: boolean;
      runtime: RuntimeOutcome;
    }> = [];

    for (const row of FILTER_RETURN_TYPE_ORACLE) {
      for (const [subscript, bucket] of [
        [`'k'`, 'keyAssign'],
        ['0', 'indexAssign'],
      ] as const) {
        const runtime = settledOutcome(row, bucket);
        const checkReports = await reportsFor(row.name, subscript);

        // `raised` is the runtime refusing the write, which is exactly when this check
        // should report. Anything else is a false block or a false approval.
        if (checkReports !== (runtime === 'raised')) {
          disagreements.push({ filter: row.name, subscript, checkReports, runtime });
        }
      }
    }

    expect(disagreements).toEqual([]);
  });

  it('sweeps the population the docset actually declares, spelling by spelling', async () => {
    // Pinned so a shrinking sweep is visible. "138 filters checked" reads the same
    // whether the docset holds 138 reporting filters or 400, and a sweep that quietly
    // stops covering 31 array filters is exactly the failure this whole file exists to
    // prevent.
    const bySpelling: Record<string, number> = {};
    for (const row of FILTER_RETURN_TYPE_ORACLE) {
      bySpelling[row.docset] = (bySpelling[row.docset] ?? 0) + 1;
    }

    expect({ total: FILTER_RETURN_TYPE_ORACLE.length, bySpelling }).toEqual({
      total: 163,
      // 138 docset names (140 rows; `map` and `split` are each listed twice) plus the 25
      // alias names the augmentation re-emits with the same return type.
      bySpelling: { string: 85, array: 43, number: 18, boolean: 17 },
    });
  });

  it('agrees with the runtime about which subscript an Array wants', async () => {
    // The rule the old check did not know, stated as a property of the whole swept
    // population rather than of one hand-picked filter: EVERY array-typed filter must
    // refuse a key and accept an index, and every other reporting type must refuse both.
    // A check that reported "not a Hash" for arrays would satisfy the sweep above for
    // keys while being wrong about every index.
    const shapes = new Set(
      FILTER_RETURN_TYPE_ORACLE.map((row) =>
        [
          row.docset === 'array' ? 'array' : 'other',
          settledOutcome(row, 'keyAssign'),
          settledOutcome(row, 'indexAssign'),
        ].join('/'),
      ),
    );

    expect([...shapes].sort()).toEqual(['array/raised/rendered', 'other/raised/raised']);
  });
});

describe('Sweep: the filters this check deliberately says nothing about', () => {
  it('lists every spelling it refuses to interpret, and what that silences', async () => {
    // AC#5, and the reason it is worth a test: the silent population is invisible in the
    // check's source, which names only the five spellings it DOES accept. Everything
    // else becomes `untyped` by falling through a `??`. That is the safe direction — a
    // missed detection, never a false block — but a NEW spelling appearing here is a
    // group of filters the check just went blind to, and it should arrive as a failure.
    expect(UNTYPED_RETURN_TYPE_SPELLINGS).toEqual({
      '': ['array_index_of'],
      '(absent)': ['new_line_to_br', 'nl2br'],
      'array of arrays': ['parse_csv', 'parse_csv_rc'],
      date: ['add_to_date', 'date_add', 'to_date'],
      datetime: ['to_time'],
      'string, nil': ['l', 'localize'],
      time: ['add_to_time'],
      untyped: [
        'array_detect',
        'deep_clone',
        'default',
        'delete_hash_key',
        'detect',
        'dig',
        'fetch',
        'first',
        'hash_delete_key',
        'hash_dig',
        'hash_fetch',
        'last',
        'remove_hash_key',
      ],
    });
  });

  it('separates the Hash-typed filters, which are silent because they are VALID targets', async () => {
    // Not the same fact as the list above and must not be read as one. `hash` is a
    // spelling the check RECOGNISES; it maps to `object`, and a Hash is a legitimate
    // hash_assign target, so silence here is a correct verdict rather than ignorance.
    expect(HASH_RETURN_TYPE_FILTERS).toEqual([
      'add_hash_key',
      'array_group_by',
      'assign_to_hash_key',
      'extract_url_params',
      'group_by',
      'hash_add_key',
      'hash_except',
      'hash_merge',
      'hash_sort',
      'jwt_decode',
      'parse_json',
      'parse_xml',
      'to_hash',
      'useragent',
      'video_params',
      'xml_to_hash',
    ]);
  });

  it('reports nothing for an untyped filter, whichever subscript is used', async () => {
    // The silence asserted as BEHAVIOUR, not just as a listing. One representative per
    // unrecognised spelling, both subscripts — the listing above proves the mapping is
    // known, this proves it is honoured.
    const representatives = Object.values(UNTYPED_RETURN_TYPE_SPELLINGS).map((names) => names[0]);

    const reports = await Promise.all(
      representatives.flatMap((name) =>
        [`'k'`, '0'].map(async (subscript) => ({
          filter: name,
          subscript,
          reports: await reportsFor(name, subscript),
        })),
      ),
    );

    expect(reports.filter((entry) => entry.reports)).toEqual([]);
  });
});
