import { describe, expect, it } from 'vitest';

import {
  DOCSET_RETURN_TYPES,
  DOCSET_RETURN_TYPE_GAPS,
  InvalidHashAssignTarget,
  variableTypeOf,
} from './index';
import {
  FILTER_RETURN_TYPE_ORACLE,
  HASH_RETURN_TYPE_FILTERS,
  UNTYPED_RETURN_TYPE_SPELLINGS,
  type FilterReturnTypeMeasurement,
  type RuntimeOutcome,
} from './filter-return-type-oracle';
import filtersJson from '../../../../platformos-check-docs-updater/data/filters.json';
import { runLiquidCheck } from '../../test';
import type { PlatformOSDocset } from '../../types';

/**
 * THE SWEEP. Every filter whose docset `return_type` makes this check willing to report,
 * driven through `assign` then `hash_assign` with both kinds of subscript, and settled
 * against what a live instance actually did.
 *
 * WHY ALL OF THEM AND NOT A SAMPLE. 173 filter names reach a reporting type, and this
 * check BLOCKS: a single wrong `return_type` among them is an unappealable refusal of
 * working code. Checking a dozen and finding them all correct says nothing about the
 * other 161, because sampling an accepting population cannot find an over-accepting
 * member. That is the same structural blindness that let twelve fictional names survive
 * in `undocumentedFilters` until a full sweep replaced the spot checks, and it is why
 * this file exists rather than a few more hand-picked cases.
 *
 * 173, NOT 140. Three things separate the docset's row count from the check's reach, and
 * each of them is a way a sweep can look complete while missing names:
 *
 *   140 reporting rows -> 138 names   `map` and `split` are each listed twice
 *   +28 alias names                   `expandAliases` re-emits every entry under each
 *                                     alias, `return_type` included, so `to_json`, `t`,
 *                                     `select`, `sort_by`, `map_attributes` and 23 more
 *                                     are reportable without appearing in filters.json
 *   +7 narrowed / gap-typed names     the date, datetime, time and array-of-arrays
 *                                     spellings, plus the two filters the docset carries
 *                                     no return_type for at all
 *
 * THE MEASUREMENTS ARE NOT MADE HERE. `filter-return-type-oracle.ts` is generated by
 * `scripts/verify-filter-return-types.mjs` against a real instance and committed; this
 * file is hermetic and runs in CI. The two halves are what make the sweep bite:
 *
 *   - the ORACLE says what the runtime does
 *   - this SPEC drives the real check over the real `filters.json`
 *
 * so a docset update that changes a `return_type` fails here instead of quietly changing
 * what the server refuses to write. When it does fail, re-run the generator: the fix is
 * either a corrected mapping in the check or a corrected row in the docset, and the
 * failure names which filter to look at.
 *
 * THE RESULT OF THE FIRST FULL SWEEP was that the docset is right about every one of the
 * 173, aliases and narrowed spellings included. That is a negative result, and it is worth having: the largest
 * unexamined surface in this check turned out to hold no over-accepting entry, and it is
 * now pinned rather than re-argued.
 */

/**
 * Types that make the check REPORT. `object` and `untyped` are the two that never do.
 *
 * Derived from the check's own table rather than restated, so a spelling added there is
 * automatically in scope for the sweep instead of needing this list updated too.
 */
const REPORTING_TYPES: ReadonlySet<string> = new Set<string>(
  [...Object.values(DOCSET_RETURN_TYPES), ...Object.values(DOCSET_RETURN_TYPE_GAPS)].filter(
    (type) => type !== 'object' && type !== 'untyped',
  ),
);

interface DocsetFilter {
  name: string;
  aliases?: string[];
  return_type?: Array<{ type: string }>;
}

/**
 * The reporting filters as the CHECK sees them.
 *
 * Mirrors `AugmentedPlatformOSDocset.filters()`: official entries, then one copy per
 * alias carrying the SAME return type. Order matters — the check builds a Map keyed by
 * name, so the last entry wins, which is also why `map` and `split` appearing twice in
 * `filters.json` collapses rather than conflicts.
 *
 * The undocumented filters the augmentation appends carry no `return_type` at all, so
 * they resolve to `untyped` and report nothing; they are covered by
 * `undocumented-filters.spec.ts` and are not part of this population.
 */
const reportingFromDocset = (): Map<string, string> => {
  const official = filtersJson as DocsetFilter[];
  const aliases = official.flatMap((filter) =>
    (filter.aliases ?? []).map((alias) => ({ ...filter, name: alias })),
  );

  const byName = new Map<string, string>();
  for (const filter of [...official, ...aliases]) {
    // The CHECK'S OWN resolver, not a reimplementation of it. Restating the mapping here
    // would let the sweep agree with a copy of the rules while the real ones drifted.
    const modelled = variableTypeOf(filter);
    if (!REPORTING_TYPES.has(modelled)) continue;
    byName.set(filter.name, modelled);
  }
  return byName;
};

/**
 * The real docset, handed to the check exactly as the runtime would.
 *
 * Deliberately NOT a hand-written mock. A mock proves the check can read a return type;
 * only the shipped data proves it reads THIS return type, for all 173, which is the
 * whole question. It is passed RAW: `runLiquidCheck` goes through the engine's own
 * `check()`, which wraps it in `AugmentedPlatformOSDocset` — so the aliases are expanded
 * by the real code path rather than by anything this file arranges.
 */
const docset = {
  async filters() {
    return filtersJson;
  },
  async objects() {
    return [];
  },
  async tags() {
    return [];
  },
  async graphQL() {
    return null;
  },
} as unknown as PlatformOSDocset;

/**
 * Whether the check reports on `{% assign x = 'a' | <name> %}{% hash_assign x[…] %}`.
 *
 * THE ARGUMENTS ARE IRRELEVANT AND THAT IS THE POINT: the check reads the LAST filter's
 * name and looks its return type up in the docset. It never evaluates arguments, so
 * `'a' | ecdh_compute` exercises it identically to the fully-formed call the generator
 * had to build for the runtime — and no key material has to live in this repository.
 *
 * BOTH SHAPES ARE RUN because this check has already had one boundary defect that only
 * one of them could see: a range starts at the defining tag's end offset, and Liquid tags
 * may abut with nothing between them, so `{% assign %}{% hash_assign %}` and the same
 * pair split by a newline took different paths. A sweep that used one shape would have
 * had a blind spot exactly where the last bug was.
 */
const reportsFor = async (name: string, subscript: string): Promise<boolean> => {
  const assign = `{% assign x = 'a' | ${name} %}`;
  const hashAssign = `{% hash_assign x[${subscript}] = 'v' %}`;

  const shapes = await Promise.all(
    [`${assign}${hashAssign}`, `${assign}\n${hashAssign}`].map((source) =>
      runLiquidCheck(InvalidHashAssignTarget, source, 'file.liquid', {
        platformosDocset: docset,
      }),
    ),
  );

  const [adjacent, newline] = shapes.map((offenses) => offenses.length > 0);
  if (adjacent !== newline) {
    throw new Error(
      `${name}[${subscript}]: adjacent and newline-separated shapes disagree ` +
        `(adjacent=${adjacent}, newline=${newline}). The tags abut at a single offset in ` +
        `the first shape; see findVariableType's inclusive start bound.`,
    );
  }
  return adjacent;
};

/**
 * What the runtime did, for a row the transport could not carry an answer for.
 *
 * THREE FILTERS ARE UNMEASURABLE DIRECTLY, and the reason is a property of the probe
 * rather than of the runtime: `ecdh_compute`, `gzip_compress` and `hkdf` all return
 * binary, the runtime's complaint quotes the offending value back, and the resulting
 * response is an HTTP 406 that carries no body at all.
 *
 * They are settled by COMPOSITION rather than assumption, and only where the table
 * itself supports it: every one measured `type_of` as `String`, and every OTHER row that
 * measured `String` was measured raising for both subscripts. So the outcome is read off
 * the rows that share the runtime type — and if those rows ever disagree among
 * themselves, this throws instead of picking one. An inference the data stops supporting
 * must fail loudly, not silently become a guess.
 */
const settledOutcome = (
  row: FilterReturnTypeMeasurement,
  bucket: 'keyAssign' | 'indexAssign',
): RuntimeOutcome => {
  if (row[bucket] !== 'unmeasured') return row[bucket];

  const peers = new Set(
    FILTER_RETURN_TYPE_ORACLE.filter(
      (other) =>
        other.name !== row.name &&
        other.runtimeType === row.runtimeType &&
        other[bucket] !== 'unmeasured',
    ).map((other) => other[bucket]),
  );

  if (peers.size !== 1) {
    throw new Error(
      `${row.name}.${bucket} is unmeasured and cannot be settled: rows with runtimeType ` +
        `"${row.runtimeType}" report ${peers.size === 0 ? 'nothing' : [...peers].join('/')}. ` +
        `Re-run scripts/verify-filter-return-types.mjs or measure this filter directly.`,
    );
  }
  return [...peers][0];
};

describe('Sweep: docset return types vs the runtime, for every reporting filter', () => {
  it('covers exactly the filters the shipped docset makes reportable', async () => {
    // THE TRIPWIRE. The oracle is measured data with a date on it; the docset ships
    // separately and can gain, lose or retype a filter at any time. If those two sets
    // ever differ, every assertion below is silently sweeping the wrong population — so
    // this runs first and names the difference.
    expect([...reportingFromDocset().keys()].sort()).toEqual(
      FILTER_RETURN_TYPE_ORACLE.map((row) => row.name).sort(),
    );
  });

  it('sweeps the alias names too, which appear nowhere in filters.json as filters', async () => {
    // NAMED EXPLICITLY BECAUSE THIS WAS ALMOST MISSED. The sweep was built over
    // `filters.json` and looked complete at 138 names; the check actually sees 173,
    // because `expandAliases` re-emits every entry under each alias with the parent's
    // `return_type` attached. Those 25 names are reportable, blocking, and absent from
    // the docset's own filter list — so a sweep that reads only the docset covers them
    // by accident or not at all.
    //
    // Pinned as a list rather than a count: a new alias on a reporting filter is a new
    // name this check will refuse writes for, and it should arrive as a failure that
    // says which one. Three joined the list when the date/array-of-arrays spellings and
    // the two docset holes were narrowed — `add_to_date`, `parse_csv_rc` and `nl2br`.
    expect(
      FILTER_RETURN_TYPE_ORACLE.filter((row) => row.aliasOf).map(
        (row) => `${row.name} < ${row.aliasOf}`,
      ),
    ).toEqual([
      'add_to_array < array_add',
      'add_to_date < date_add',
      'any < array_any',
      'compact < array_compact',
      'date_before < is_date_before',
      'flatten < array_flatten',
      'in_groups_of < array_in_groups_of',
      'intersection < array_intersect',
      'is_included_in_array < array_include',
      'jwe_encode_rc < jwe_encode',
      'limit < array_limit',
      'map_attributes < array_map',
      'markdownify < markdown',
      'nl2br < new_line_to_br',
      'parse_csv_rc < parse_csv',
      'prepend_to_array < array_prepend',
      'reject < array_reject',
      'rotate < array_rotate',
      'select < array_select',
      'shuffle_array < array_shuffle',
      'sort_by < array_sort_by',
      'subtract_array < array_subtract',
      'sum_array < array_sum',
      't < translate',
      't_escape < translate_escape',
      'to_json < json',
      'to_xml_rc < to_xml',
      'www_form_encode_rc < www_form_encode',
    ]);
  });

  it('resolves every filter to the type the check itself derives, not to a restated rule', async () => {
    // The other half of the tripwire: same names, same MODELLED type. A docset row
    // retyped from `array` to `string` keeps its name and changes what the check refuses,
    // and a mapping edit in `DOCSET_RETURN_TYPES` does the same without touching the
    // docset at all. Both land here, because the right-hand side runs the check's own
    // `variableTypeOf` over the shipped data.
    const modelledNow = reportingFromDocset();
    expect(
      FILTER_RETURN_TYPE_ORACLE.map((row) => ({ name: row.name, modelled: row.modelled })),
    ).toEqual(
      FILTER_RETURN_TYPE_ORACLE.map((row) => ({
        name: row.name,
        modelled: modelledNow.get(row.name),
      })),
    );
  });

  it('fills a type from the gap table ONLY where the docset has no data at all', async () => {
    // AC#3. `DOCSET_RETURN_TYPE_GAPS` is a workaround for missing upstream data, and the
    // danger is that it quietly becomes a second mapping table with weaker rules. Two
    // properties keep it honest, and both are asserted from the shipped docset:
    //
    //   1. every filter it names really does lack return-type data
    //   2. every filter that lacks return-type data is named by it
    //
    // (2) is the one that bites later: if the docset loses a `return_type` for some other
    // filter, that filter silently becomes untyped and this check goes blind to it. If
    // the docs team FIXES these two upstream, (1) fails and tells us to delete the
    // workaround — which is also the outcome we want.
    const official = filtersJson as DocsetFilter[];
    const withAliases = [
      ...official,
      ...official.flatMap((filter) =>
        (filter.aliases ?? []).map((alias) => ({ ...filter, name: alias })),
      ),
    ];

    const holes = withAliases
      .filter(({ return_type: rt }) => !rt || rt.length === 0 || (rt.length === 1 && !rt[0].type))
      .map((filter) => filter.name)
      .sort();

    expect({ holes, gapTable: Object.keys(DOCSET_RETURN_TYPE_GAPS).sort() }).toEqual({
      holes: ['array_index_of', 'new_line_to_br', 'nl2br'],
      gapTable: ['array_index_of', 'new_line_to_br', 'nl2br'],
    });
  });

  it('never refuses a hash_assign the runtime accepts, and never accepts one it refuses', async () => {
    // THE SWEEP ITSELF, in the only form that matters: the check's verdict against the
    // runtime's, for all 173 filters and both subscripts.
    //
    // Asserted as an empty list of disagreements rather than 346 separate expectations,
    // so a failure names every filter at once — a docset regression usually moves a
    // whole spelling, not one entry, and seeing "45 array filters disagree" is a
    // different diagnosis from seeing the first one fail.
    const disagreements: Array<{
      filter: string;
      subscript: string;
      checkReports: boolean;
      runtime: RuntimeOutcome;
    }> = [];

    for (const row of FILTER_RETURN_TYPE_ORACLE) {
      for (const [subscript, bucket] of [
        [`'k'`, 'keyAssign'],
        ['0', 'indexAssign'],
      ] as const) {
        const runtime = settledOutcome(row, bucket);
        const checkReports = await reportsFor(row.name, subscript);

        // `raised` is the runtime refusing the write, which is exactly when this check
        // should report. Anything else is a false block or a false approval.
        if (checkReports !== (runtime === 'raised')) {
          disagreements.push({ filter: row.name, subscript, checkReports, runtime });
        }
      }
    }

    expect(disagreements).toEqual([]);
  });

  it('sweeps the whole reportable population, type by type', async () => {
    // Pinned so a SHRINKING sweep is visible. "173 filters checked" reads the same
    // whether the check can report on 173 names or 400, and a sweep that quietly stops
    // covering 45 array filters is exactly the failure this whole file exists to prevent.
    const byModelled: Record<string, number> = {};
    for (const row of FILTER_RETURN_TYPE_ORACLE) {
      byModelled[row.modelled] = (byModelled[row.modelled] ?? 0) + 1;
    }

    expect({ total: FILTER_RETURN_TYPE_ORACLE.length, byModelled }).toEqual({
      total: 173,
      // 138 docset names (140 rows; `map` and `split` are each listed twice), plus 32
      // alias names the augmentation re-emits with the same return type, plus the three
      // filters typed only through DOCSET_RETURN_TYPE_GAPS.
      byModelled: { string: 87, array: 45, number: 19, boolean: 17, date: 3, time: 2 },
    });
  });

  it('groups the date and time spellings the way the runtime does', async () => {
    // The narrowing this sweep was extended for, asserted as data rather than as prose.
    // `datetime` and `time` collapse onto one modelled type because the runtime returns a
    // Time for both — if a future docset spelling were mapped by resemblance instead of
    // by measurement, the row would show up here without a matching runtime type.
    expect(
      FILTER_RETURN_TYPE_ORACLE.filter((row) => row.modelled === 'date' || row.modelled === 'time')
        .map((row) => `${row.name}: ${row.docsetSpelling} -> ${row.modelled} (${row.runtimeType})`)
        .sort(),
    ).toEqual([
      'add_to_date: date -> date (Date)',
      'add_to_time: time -> time (Time)',
      'date_add: date -> date (Date)',
      'to_date: date -> date (Date)',
      'to_time: datetime -> time (Time)',
    ]);
  });

  it('agrees with the runtime about which subscript an Array wants', async () => {
    // The rule the old check did not know, stated as a property of the whole swept
    // population rather than of one hand-picked filter: EVERY array-typed filter must
    // refuse a key and accept an index, and every other reporting type must refuse both.
    // A check that reported "not a Hash" for arrays would satisfy the sweep above for
    // keys while being wrong about every index.
    const shapes = new Set(
      FILTER_RETURN_TYPE_ORACLE.map((row) =>
        [
          row.modelled === 'array' ? 'array' : 'other',
          settledOutcome(row, 'keyAssign'),
          settledOutcome(row, 'indexAssign'),
        ].join('/'),
      ),
    );

    expect([...shapes].sort()).toEqual(['array/raised/rendered', 'other/raised/raised']);
  });
});

describe('Sweep: the filters this check deliberately says nothing about', () => {
  it('lists every spelling it refuses to interpret, and what that silences', async () => {
    // AC#5, and the reason it is worth a test: the silent population is invisible in the
    // check's source, which names only the five spellings it DOES accept. Everything
    // else becomes `untyped` by falling through a `??`. That is the safe direction — a
    // missed detection, never a false block — but a NEW spelling appearing here is a
    // group of filters the check just went blind to, and it should arrive as a failure.
    // Down to two spellings, and both are here on purpose rather than for want of a
    // measurement. `untyped` describes values whose type depends on what was piped in —
    // `first` of an Array of Hashes is a Hash — and `'string, nil'` is a union. No single
    // probe can establish either, so silence stays the only safe reading. The four
    // spellings that USED to be listed here (date, datetime, time, array of arrays) were
    // narrowed once the runtime settled them; see DOCSET_RETURN_TYPES.
    expect(UNTYPED_RETURN_TYPE_SPELLINGS).toEqual({
      'string, nil': ['l', 'localize'],
      untyped: [
        'array_detect',
        'deep_clone',
        'default',
        'delete_hash_key',
        'detect',
        'dig',
        'fetch',
        'first',
        'hash_delete_key',
        'hash_dig',
        'hash_fetch',
        'last',
        'remove_hash_key',
      ],
    });
  });

  it('separates the Hash-typed filters, which are silent because they are VALID targets', async () => {
    // Not the same fact as the list above and must not be read as one. `hash` is a
    // spelling the check RECOGNISES; it maps to `object`, and a Hash is a legitimate
    // hash_assign target, so silence here is a correct verdict rather than ignorance.
    expect(HASH_RETURN_TYPE_FILTERS).toEqual([
      'add_hash_key',
      'array_group_by',
      'assign_to_hash_key',
      'extract_url_params',
      'group_by',
      'hash_add_key',
      'hash_except',
      'hash_merge',
      'hash_sort',
      'jwt_decode',
      'parse_json',
      'parse_xml',
      'to_hash',
      'useragent',
      'video_params',
      'xml_to_hash',
    ]);
  });

  it('reports nothing for an untyped filter, whichever subscript is used', async () => {
    // The silence asserted as BEHAVIOUR, not just as a listing. One representative per
    // unrecognised spelling, both subscripts — the listing above proves the mapping is
    // known, this proves it is honoured.
    const representatives = Object.values(UNTYPED_RETURN_TYPE_SPELLINGS).map((names) => names[0]);

    const reports = await Promise.all(
      representatives.flatMap((name) =>
        [`'k'`, '0'].map(async (subscript) => ({
          filter: name,
          subscript,
          reports: await reportsFor(name, subscript),
        })),
      ),
    );

    expect(reports.filter((entry) => entry.reports)).toEqual([]);
  });
});
