import { describe, expect, it } from 'vitest';

import { FilterArity } from './index';
import { FILTER_ARITY } from '../../filter-arity';
import { check, MockApp } from '../../test';

/**
 * TASK-28 (evaluation finding F-07). A KNOWN filter called with the wrong number of
 * arguments used to pass validation and then raise at render time:
 *
 *   {{ 'abc' | slice }}   ->  ok / must_fix_before_write: false
 *                             Liquid::ArgumentError — wrong number of arguments
 *                             (given 1, expected 2..3), page HTTP 500
 *
 * The asymmetry was the finding: an unknown filter NAME blocked the write while a
 * known filter called wrongly — the same class of runtime failure — was approved.
 *
 * Every expected range below is the runtime's own number, generated by
 * `scripts/verify-filter-arity.mjs`, so these fixtures and the data agree by
 * construction rather than by a second hand-typed opinion.
 */
const offensesFor = (liquid: string) => {
  const app: MockApp = { 'app/views/partials/file.liquid': liquid };
  return check(app, [FilterArity]);
};

const messages = async (liquid: string) =>
  (await offensesFor(liquid)).map((offense) => offense.message);

describe('Module: FilterArity', () => {
  describe('reports a call the runtime would reject', () => {
    it('reports too few arguments', async () => {
      // slice is 2..3; the piped value alone is 1.
      expect(await messages(`{{ 'abc' | slice }}`)).toEqual([
        "Filter 'slice' is called with 1 argument but accepts 2 to 3 (the piped value counts as one). platformOS raises Liquid::ArgumentError at render time.",
      ]);
    });

    it('reports too many arguments', async () => {
      // upcase is exactly 1, so any explicit argument is one too many.
      expect(await messages(`{{ 'abc' | upcase: 1, 2, 3 }}`)).toEqual([
        "Filter 'upcase' is called with 4 arguments but accepts exactly 1 (the piped value counts as one). platformOS raises Liquid::ArgumentError at render time.",
      ]);
    });

    it('reports the other filter named in the evaluation', async () => {
      expect(await messages(`{{ 'abc' | replace }}`)).toEqual([
        "Filter 'replace' is called with 1 argument but accepts 2 to 3 (the piped value counts as one). platformOS raises Liquid::ArgumentError at render time.",
      ]);
    });

    it('reports each offending filter in a chain independently', async () => {
      expect(await messages(`{{ 'abc' | slice | replace }}`)).toHaveLength(2);
    });
  });

  describe('counts arguments the way the runtime does', () => {
    it('treats a whole group of named arguments as ONE argument', async () => {
      // MEASURED: `{{ 'abc' | upcase: a: 1, b: 2, c: 3 }}` is "given 2", not 4.
      // Counting the three names separately would report this as 4 and refuse a
      // pattern the runtime merely type-errors on — the single most likely way for
      // this check to become a source of false blocks.
      expect(await messages(`{{ 'abc' | upcase: a: 1, b: 2, c: 3 }}`)).toEqual([
        "Filter 'upcase' is called with 2 arguments but accepts exactly 1 (the piped value counts as one). platformOS raises Liquid::ArgumentError at render time.",
      ]);
    });

    it('mixes positional and named arguments the way the runtime does', async () => {
      // MEASURED: `{{ 'abcdef' | slice: 1, 2, extra: 9 }}` is "given 4" — input + two
      // positional + one hash — which is one past slice's maximum of 3.
      expect(await messages(`{{ 'abcdef' | slice: 1, 2, extra: 9 }}`)).toEqual([
        "Filter 'slice' is called with 4 arguments but accepts 2 to 3 (the piped value counts as one). platformOS raises Liquid::ArgumentError at render time.",
      ]);
    });

    it('counts the piped value as argument one', async () => {
      // slice's minimum of 2 is satisfied by the input plus ONE explicit argument.
      // If the input were not counted this would read as 1 and be reported.
      expect(await messages(`{{ 'abcdef' | slice: 1 }}`)).toEqual([]);
    });
  });

  describe('stays silent where it cannot be sure', () => {
    it('says nothing about a filter with no measured arity', async () => {
      // `dig` is variadic, so the generator recorded no range for it. Unknown must
      // stay unknown: a module-provided or newly-added filter must never be refused
      // just because this data has not caught up.
      expect(FILTER_ARITY.dig).toBeUndefined();
      expect(await messages(`{{ 'abc' | dig: 'a', 'b', 'c', 'd' }}`)).toEqual([]);
    });

    it('says nothing about a filter that does not exist at all', async () => {
      // That is `UnknownFilter`'s question, not this check's. Reporting here too would
      // double up on one mistake.
      expect(await messages(`{{ 'abc' | no_such_filter_xyz: 1, 2, 3, 4, 5 }}`)).toEqual([]);
    });
  });

  describe('accepts correct calls across every arity shape', () => {
    it.each([
      ['exact arity, no arguments', `{{ 'abc' | upcase }}`],
      ['ranged arity, at the minimum', `{{ 'abcdef' | slice: 1 }}`],
      ['ranged arity, at the maximum', `{{ 'abcdef' | slice: 1, 2 }}`],
      ['ranged arity, in the middle', `{{ 'now' | add_to_time: 1, 'days' }}`],
      ['a named-argument call within range', `{{ 'abc' | truncate: length: 3 }}`],
      ['an alias, which carries its own arity', `{{ 'key' | t }}`],
      ['a generated undocumented filter', `{% assign a = '' | split: ',' %}{{ a | sum }}`],
    ])('%s', async (_label, liquid) => {
      expect(await messages(liquid)).toEqual([]);
    });
  });

  describe('the arity data it depends on', () => {
    it('carries the ranges measured from the runtime for the reported cases', () => {
      // Pins the fixtures above to the generated data. If a regeneration changed
      // slice or upcase, the expectations in this file would be silently wrong rather
      // than failing for a reason anyone could read.
      expect([FILTER_ARITY.slice, FILTER_ARITY.upcase, FILTER_ARITY.replace]).toEqual([
        { min: 2, max: 3 },
        { min: 1, max: 1 },
        { min: 2, max: 3 },
      ]);
    });
  });
});
